services:
  nextjs-app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    volumes:
      - .:/app
    command: npm run dev
